zero-to-mastery/complete-web-developer-manual

README.md
Added the option to choose vscode as a text editor.
=> added vscode option

README.md
added The Complete Junior to Senior Web Developer Roadmap (2019)
=> added junior to senior udemy course

README.md
add coolors.co as a color reference
=> add coolors.co as a color reference

README.md
Hello - I made some minor typo/punctuation/spelling fixes throughout the document, and some edits to the commands for the postgresSQL section at the end.
There were a few minor translations of the instructions from Spanish as well.
Please review and let me know what you think.
Cheers!
=> typo, spelling, minor formatting edits

README.md
added flexbox froggy to the advanced css section
=> added missing sections and links

README.md
Hello! I've changed the command line section for Mac and Linux to use a table format and changed any uppercase letters to lowercase since macOS and Linux file systems are case sensitive. Let me know what you think :)
=> Changes commands to lowercase and uses table format

index.html
Adding an index file to the project
=> adding index file

README.md
added links to popular code editors covered in section 15
=> Updated 15. Developer Environment section

README.md
Switched particles library to the official tsParticles react library
=> Switched particles library

README.md
Added a link for the grid system in the CSS references.
=> Added link for grid system resource.

README.md
I've added a linked table of content for easier navigation.
=> add linked content

README.md
Format table of contents: with italics, no bold.
=> Format Table of Contents

README.md
- Includes pseudo element in CSS selectors list.
- Deletes all unnecessary whitespace.
=> Documentation - Include pseudo element in CSS selectors list

README.md
Created content for the topic "10. Career Of A Web Developer".
=> Created content for 10. Career of a Web Developer

README.md
- Added development environment stack tools for Mac & Windows.
- Fixed typo on Brackets
=> Added dev env stacks

README.md
Added: **display: inline-block** in CSS properties
=> Remove unnecessary word(html)

README.md
add code formatting in chapter 13 
i.e. `let variableName;` instead of let variable name;
=> add code formatting in chapter 13

README.md
I've added Information of DOM Selectors to chapter 12. DOM Manipulation.
=> added DOM Selectors to chapter 12. DOM Manipulation

README.md
Please review my changes and see if you approve. Thank you.
=> I have edited formatting and sub headings, added some of my own info.

README.md
=> Update code format

README.md
Added code blocks for conditional statements and descriptions for basic javascript and also updated animate.css website
=> Some additions and updations

README.md
Hi, I added two git commands. @matteobruni
=> added two git commands

README.md
fixed some misspellings in the Advanced Javascript section
=> Fixed misspellings

README.md
I have added information about the list of the best platforms for jobs and careers, where anyone can find a way to grow their career or get a job easily.
=> Added info about best platforms for career growth

README.md
Added some online HTML editors + an HTML reference.
=> added resources for html

README.md
Addition of useful github and version control learning playground/website
lines 684-686
=> added git playground website url

README.md
Added link of video for learning Git and GitHub, This video will surely help new developers to learn Git and GitHub with the help of very practical examples, this video is more useful for developers especially from India.
=> Git in one video added

README.md
lines 700, 702, 709
Extra git commits and description here
700 - "git add" and "git commit -m 'msg'  both be done with one command
702 - creates new branch and commits the changes or code to the repo globally with the branch name specified
709 - outputs the difference with last commit and current file in the terminal for a specific file mentioned
=> add extra git commands

README.md
Addition of NVM resource to install multiple versions of node and change between them for each project.
lines 768-769
=> added NVM resource to manage multiple node versions

README.md
Fixing the typo in linking the external css
=> Adding a double apostrophe

README.md
Added useful links for running multiple node versions on the system.
=> Added useful link for running multiple Node version

README.md
Adding some changes to javascript data type BigInt is missing and adding primitive and Non-primitive types @MattCSmith
=> Added some changes to JS data types
